name: Docker Smoke Test

on:
  push:
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-smoke-test.yml'
  pull_request:
    paths:
      - 'Dockerfile'

jobs:
  smoke-test:
    permissions: 
      contents: read

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t dape:test .

      - name: Run container
        run: |
          docker run --rm dape:test --version || (echo "Container failed to start" && exit 1)
